name: Test

on: [push, pull_request, workflow_dispatch]

jobs:

  checks:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - run: |
          git submodule update --init --recursive
          nix flake check
